### ISSUE TITLE
InfluxDB 0.9 integration broken

### ISSUE THREAD

**Issue by timbuchwaldt** [aphyr/riemann#574]
Sadly InfluxDB changed their support for JSON during the RC-progress to 0.9. Changed as in just deactivated, so now we need to send line protocol: https://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html

I will try and come up with a function to encodes events in that very under-defined format.

**Comment by aphyr** [comment]
Is this addressed by https://github.com/aphyr/riemann/pull/555?

**Comment by robashton** [comment]
Doesn't look like it @aphyr  - #555 still uses json for comms

**Comment by robashton** [comment]
I could look at this on Monday (with #555 as the start point if nobody else does, influx still "works" with JSON but in a slightly hobbled fashion.

**Comment by robashton** [comment]
Ooh #575 <3

**Comment by greglook** [comment]
InfluxDB 0.9.0 _does_ support JSON, they just made a backwards-incompatible change to the API. All you need to do is pass `:measurement` instead of `:name` [here](https://github.com/aphyr/riemann/blob/3534463855a08633abf8e7103f75a8ef525a51e7/src/riemann/influxdb.clj#L51). I'll open a PR to copy over the updates we've made once switching to 0.9.0.
